config/routes.rb
Rails.application.routes.draw do
  root 'persons#index'
  resources :persons  do
    resources :person_details
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
    has_one :person_detail, dependent: :destroy

    validates :email, presence: true
    validates :email, uniqueness: true
    validates :name, presence: true
end

app/models/person_detail.rb
class PersonDetail < ApplicationRecord
  belongs_to :person
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/person_details_controller.rb
class PersonDetailsController < ApplicationController
    before_action :find_person
    before_action :find_person_detail, only: %i[show edit update destroy]

    def index
         @person_detail = PersonDetail.all.includes(:persons)
         render json: {status: :ok}
    end
      
    def new
        @person_detail = PersonDetail.new
    end

    def create
        if @person.person_detail.present?
            @person_detail = @person.person_detail.build(person_detail_params)
          else
            @person_detail = @person.build_person_detail(person_detail_params)
          end
        
          if @person_detail.save
            redirect_to persons_path, notice: 'Person detail was successfully created.'
          else
            render :new
          end
    end

      def update
            @person_detail.update(person_detail_params)
            redirect_to person_person_detail_path(@person, @person_detail), message: "Person details was successfully Updated."
      end

      def show
        @person_detail
      end

      def destroy
        @person_detail.destroy
        redirect_to persons_path, notice: "Person details was successfully destroyed."
      end


      private
      
      def find_person
        @person = Person.find(params[:person_id])
      end

      def find_person_detail
        @person_detail = @person.person_detail
      end
      def person_detail_params
        params.require(:person_detail).permit(:title, :age, :phone)
      end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
    before_action :find_person, except: %i[create index new]

    def index
         @persons = Person.all
    end
      
    def new
        @person = Person.new
    end

    def create
        @person = Person.new(person_params)
        
        if @person.save
          redirect_to persons_path, notice: "Person was successfully created."
        else
          render json: { errors: @person.errors.full_messages }, status: :unprocessable_entity
        end
    end


    def update
        unless @person.update(person_params)
          redirect_to persons_path, notice: "Person was successfully Updated.", status: :ok
         else
             render json: @person, status: :ok
        end
    end

    def show
        render json: @person
    end

    def destroy    
        @person.destroy
        redirect_to persons_path, notice: "Person was successfully destroyed."
    end


    private
    
    def find_person
      @person = Person.find(params[:id])
    end
    def person_params
      params.require(:person).permit(:name, :email )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/person_details_helper.rb
module PersonDetailsHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DetailManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <%= yield %>
  </body>
</html>

app/views/person_details/edit.html.erb
<%= stylesheet_link_tag 'application' %>

<h1>Update person detail</h1>
<%= form_with(model: [@person, @person_detail], url: person_person_detail_path(@person, @person_detail), method: :patch, local: true) do |form| %>


  <% if @person_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person_detail.errors.count, "error") %> prohibited this person_detail from being saved:</h2>
      <ul>
        <% @person_detail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
    <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>
  </div>
    <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<br>
  <%= button_to 'Back', persons_path, method: :get%>

app/views/person_details/new.html.erb
<%= stylesheet_link_tag 'application' %>

<h1>Add person detail</h1>
<%= form_with(model: @person_detail, url: person_person_details_path, local: true) do |form| %>

  <% if @person_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person_detail.errors.count, "error") %> prohibited this person_detail from being saved:</h2>
      <ul>
        <% @person_detail.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
    <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>
    <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/person_details/show.html.erb
<%= stylesheet_link_tag 'application' %>

<h1>Persons details</h1>
<table>
  <thead>
    <tr>
      <th>Person ID</th>
      <th>Person name</th>
      <th>Person email</th>
      <th>title</th>
      <th>age</th>
      <th>phone</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @person_detail&.person_id %></td>
        <td><%= @person&.name %></td>
        <td><%= @person&.email %></td>
        <td><%= @person_detail&.title %></td>
        <td><%= @person_detail&.age %></td>
        <td><%= @person_detail&.phone %></td>
      </tr>
  </tbody>
</table>
  <%= button_to 'Back', persons_path, method: :get%>

app/views/persons/_index_person.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>
  <%= link_to "Create person", new_person_path, data: { "turbo-method": :post } %>
  <tbody>
    <% @persons.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
 <td><%= button_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
<%
=begin%>
 <td><%= button_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?', turbo_method: :delete } %></td> 
<%
=end%>
        <% unless user.person_detail.present? %>
          <td><%= button_to 'Add details', new_person_person_detail_path(user.id), method: :get %></td>
        <% else %>
          <td><%= button_to 'Update details', edit_person_person_detail_path(user.id, user.person_detail.id), method: :get  %></td>

         <td><%= button_to 'Show details', person_person_detail_path(user, user.person_detail), method: :get  %></td>

        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/persons/edit.html.erb
<%= stylesheet_link_tag 'application' %>

<h1>Edit person</h1>
<%= form_with(model: @person, url: persons_path(@person.id), local: true) do |form| %>

  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>
      <ul>
        <% @person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/persons/index.html.erb
<div class="banner">
    <p>Details management</p>
</div>
<h2>Persons</h2>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Delete action</th>
      <th>Update action</th>
      <th>Show action</th>

    </tr>
  </thead>
  <%= button_to "Create person", new_person_path, data: { "turbo-method": :post }, method: :get %>
  <tbody>
    <% @persons.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
 <td><%= button_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td> 
<%
=begin%>
 <td><%= button_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?', turbo_method: :delete } %></td> 
<%
=end%>
        <% unless user.person_detail.present? %>
          <td><%= button_to 'Add details', new_person_person_detail_path(user.id), method: :get %></td>
        <% else %>
          <td><%= button_to 'Update details', edit_person_person_detail_path(user.id, user.person_detail.id), method: :get  %></td>

         <td><%= button_to 'Show details', person_person_detail_path(user, user.person_detail), method: :get  %></td>

        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/persons/new.html.erb
<%= stylesheet_link_tag 'application' %>

<h1>New person</h1>
<%= form_with(model: @person, url: persons_path, local: true) do |form| %>

  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>
      <ul>
        <% @person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>